dist: bionic
addons:
  snaps:
    - hugo

install:
  - cd ./src/
  - git submodule update --init --remote

script:
  - hugo -D

after_script:
  - cd ..
  - git config --global user.name "Travis CI"
  - git config --global user.email "cloxnu@outlook.com"
  - git add .
  - git commit -m "Update Blog By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  - git push
