# This is a basic workflow to help you get started with Actions

name: build creative.clox.nu

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          
      - name: Move files to gh-pages
        run: |
          git checkout main -- src
          git checkout main -- .gitmodules

      # Update theme 
      - name: Update theme
        run: git submodule update --init --recursive

      # Setup Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
        
      # Build blog
      - name: Build
        working-directory: ./src/
        run: hugo
        
      - name: Move files to gh-pages
        run: |
          mv docs/* .
          rm -r docs/
          rm -r src/
          rm .gitmodules
        
      # Commit & Push
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
